dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
install:
  - yarn install --ignore-engines
  - yarn global add codecov
before_script:
  - yarn lerna run lint
script:
  - yarn lerna run test --stream
  - codecov
       
stages:
  - test
  - test_locales
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: test_locales
      before_install:
        - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-en language-pack-fr
        - sudo locale-gen fr_FR.UTF-8
      script: LANG="fr_FR.UTF8" LC_ALL="fr_FR.UTF8" yarn lerna run test --stream
      
    - stage: deploy
      node_js: "10"
      skip_cleanup: true
      if: branch = master
      script: 
        - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout master
        - yarn lerna publish
